services:
  mongodb:
    image: mongo:8.0.6
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - "27017:27017"